import { NextResponse } from 'next/server'
import type { Product } from '@shop/api-client'

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p-1',
    name: 'Oakwood Platform Bed Frame',
    price: 749,
    category: 'beds',
    subcategory: 'platform',
    material: 'Solid Oak',
    gradient: 'linear-gradient(135deg, #c2a986 0%, #8b6f4d 100%)',
    description:
      'A clean-lined platform bed in solid European oak. Slatted base, no boxspring needed. Hand-finished with natural wax oil.',
    rating: 4.8,
    reviewCount: 1241,
    isBestseller: true,
  },
  {
    id: 'p-2',
    name: 'Linen Upholstered Headboard',
    price: 489,
    category: 'beds',
    subcategory: 'upholstered',
    material: 'French Linen',
    gradient: 'linear-gradient(135deg, #e8e2d5 0%, #b8a98a 100%)',
    description: 'Soft, oversized headboard in stonewashed French linen. Removable cover.',
    rating: 4.7,
    reviewCount: 870,
    isNew: true,
  },
  {
    id: 'p-3',
    name: 'Walnut Four-Poster Bed',
    price: 1299,
    category: 'beds',
    subcategory: 'four-poster',
    material: 'American Walnut',
    gradient: 'linear-gradient(135deg, #6b4a30 0%, #3d2818 100%)',
    description: 'Hand-built four-poster in dark American walnut. Mortise-and-tenon joinery throughout.',
    rating: 4.9,
    reviewCount: 542,
    isBestseller: true,
  },
  {
    id: 'p-4',
    name: 'Cloudfoam Hybrid Mattress',
    price: 899,
    category: 'mattresses',
    subcategory: 'hybrid',
    material: 'Pocket Spring + Memory Foam',
    gradient: 'linear-gradient(135deg, #f5f1ea 0%, #d4cdb9 100%)',
    description: 'Medium-firm hybrid with 2,000 individually wrapped pocket springs and a cooling gel comfort layer.',
    rating: 4.7,
    reviewCount: 3120,
    isNew: true,
  },
  {
    id: 'p-6',
    name: 'Memory Foam Pocket Mattress',
    price: 599,
    category: 'mattresses',
    subcategory: 'memory-foam',
    material: 'CertiPUR Memory Foam',
    gradient: 'linear-gradient(135deg, #ddd3bf 0%, #968264 100%)',
    description: 'Five-zone memory foam mattress with a removable, washable cover.',
    rating: 4.6,
    reviewCount: 2410,
  },
  {
    id: 'p-7',
    name: 'Velvet Wingback Headboard',
    price: 549,
    originalPrice: 689,
    category: 'beds',
    subcategory: 'upholstered',
    material: 'Cotton Velvet',
    gradient: 'linear-gradient(135deg, #4a5d52 0%, #2a3833 100%)',
    description: 'Wingback headboard in deep emerald cotton velvet with hand-applied piping detail.',
    rating: 4.8,
    reviewCount: 1140,
    isBestseller: true,
  },
  {
    id: 'p-8',
    name: 'Brass Bedside Lamp',
    price: 159,
    originalPrice: 199,
    category: 'sale',
    material: 'Solid Brass',
    gradient: 'linear-gradient(135deg, #d9b67e 0%, #8b6c3e 100%)',
    description: 'Cast-brass cone shade with a marble base. Warm dimmable LED included.',
    rating: 4.5,
    reviewCount: 412,
  },
  {
    id: 'p-9',
    name: 'Stonewashed Linen Duvet Set',
    price: 189,
    originalPrice: 249,
    category: 'sale',
    material: 'Belgian Linen',
    gradient: 'linear-gradient(135deg, #e2dccb 0%, #a99e85 100%)',
    description: 'Pre-washed Belgian linen duvet cover with two pillowcases. King size. Ten colourways.',
    rating: 4.9,
    reviewCount: 2840,
    isBestseller: true,
  },
  {
    id: 'p-10',
    name: 'Rattan Storage Bench',
    price: 329,
    originalPrice: 399,
    category: 'sale',
    material: 'Hand-Woven Rattan',
    gradient: 'linear-gradient(135deg, #d6b884 0%, #8c6d40 100%)',
    description: 'Lift-top rattan storage bench. Solid wood frame, deep enough for two duvet sets.',
    rating: 4.6,
    reviewCount: 318,
    isNew: true,
  },
  {
    id: 'p-11',
    name: 'Reeded Oak Bedside Table',
    price: 269,
    category: 'beds',
    material: 'Reeded Oak Veneer',
    gradient: 'linear-gradient(135deg, #c9a473 0%, #765636 100%)',
    description: 'Two-drawer bedside in reeded oak veneer with brushed brass pull handles.',
    rating: 4.7,
    reviewCount: 612,
    isNew: true,
  },
  {
    id: 'p-12',
    name: 'Pocket Sprung Quilted Mattress Topper',
    price: 129,
    category: 'mattresses',
    material: 'Quilted Cotton',
    gradient: 'linear-gradient(135deg, #f0e8d4 0%, #c5b793 100%)',
    description: 'Adds a soft cotton-filled layer on top of any mattress. Elasticated corners fit up to 35cm.',
    rating: 4.5,
    reviewCount: 1880,
  },
]

export async function GET() {
  return NextResponse.json(MOCK_PRODUCTS)
}
